FROM node:18

WORKDIR /app
COPY . .

# Install dependencies
RUN npm install

# Build the worker
RUN npx tsc -p worker/tsconfig.worker.json

# Run the built worker
CMD ["node", "dist/worker/worker.js"]
