services:
  - type: private_service
    name: valkey
    env: docker
    dockerfilePath: ''
    image: valkey/valkey
    plan: free
    ports:
      - 6379

  - type: private_service
    name: qdrant
    env: docker
    dockerfilePath: ''
    image: qdrant/qdrant
    plan: free
    ports:
      - 6333

  - type: worker
    name: paperfy-worker
    env: docker
    dockerfilePath: Dockerfile.worker
    plan: free
    envVars:
      - key: REDIS_URL
        value: redis://valkey:6379
      - key: QDRANT_URL
        value: http://qdrant:6333
      - key: API_BASE_URL
        value: https://paperfy.vercel.app
