services:
  - type: pserv
    name: valkey
    runtime: docker
    image: 
      url: valkey/valkey
    plan: free
    

  - type: pserv
    name: qdrant
    runtime: docker
    image: 
      url: qdrant/qdrant
    plan: free

  - type: worker
    name: paperfy-worker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - key: REDIS_URL
        value: redis://valkey:6379
      - key: QDRANT_URL
        value: http://qdrant:6333
      - key: API_BASE_URL
        value: https://your-vercel-app.vercel.app
      - key: COHERE_API_KEY
        value: pxHHZy29DAsfH6TybW85qOuGB7OnHDfEcfaBUy0j
      - key: GOOGLE_API_KEY
        value: AIzaSyBc0hFj0HTP-R3CEkWEKZGlUeZayOcbxKs

