services:
  - type: pserv
    name: valkey
    runtime: docker
    image: 
      url: valkey/valkey
    plan: starter
    disk: # Optional: Add if persistence is needed
      name: valkey-data
      mountPath: /data
      sizeGB: 10

  - type: pserv
    name: qdrant
    runtime: docker
    image: 
      url: qdrant/qdrant
    plan: starter
    disk: # Optional: Add if persistence is needed
      name: qdrant-data
      mountPath: /qdrant/storage
      sizeGB: 10

  - type: worker
    name: paperfy-worker
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.worker
    repo: https://github.com/your-org/your-repo # Add if needed
    branch: main # Optional: Specify branch
    envVars:
      - key: REDIS_URL
        value: redis://valkey:6379
      - key: QDRANT_URL
        value: http://qdrant:6333
      - key: API_BASE_URL
        value: https://paperfy.vercel.app # Replace with actual URL
      - key: COHERE_API_KEY
        sync: false # Prompt in Render Dashboard
      - key: GOOGLE_API_KEY
        sync: false # Prompt in Render Dashboard